const config = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  RPC_URL: process.env.NEXT_PUBLIC_TEST_RPC_URL,
  MONGODB_URI: process.env.NEXT_PUBLIC_TEST_MONGODB_URI,
  ORACLE_CONTRACT_ADDRESS: process.env.NEXT_PUBLIC_TEST_ORACLE_CONTRACT_ADDRESS,
  LOAN_POSITION_MANAGER_ADDRESS: process.env.NEXT_PUBLIC_LOAN_POSITION_MANAGER_ADDRESS,
  NETWORK_ID: process.env.NEXT_PUBLIC_NETWORK_ID,
};

export const test_config = {
  TOKEN_A: process.env.NEXT_PUBLIC_TOKEN_A_ADDRESS,
  TOKEN_B: process.env.NEXT_PUBLIC_TOKEN_B_ADDRESS,
}

export default config;
